# Generated by Django 6.0.7 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured_product_rating_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
